### ISSUE TITLE
Incorrect Handling of Crtl+C

### ISSUE THREAD

**Issue by Fabianstw** [SpitzkopfLarry/MiniShell#1] opened 2024-06-09 10:50 UTC
After pressing `Crtl+C` the program still needs to finish the while loop and does not quit directly after entering `y`.

**Comment by SpitzkopfLarry** [comment] 2024-06-09 10:54
Good eyes buddy! After looking at the code, there is a error with the Singal Handling. The issue is fixed now. For further questions I am at your disposal.

**Closed** 2024-06-09 12:38 UTC
